version: '3'
services:
  mytournamentx-api:
    image: udlepssoftarch/mytournamentx-api
    container_name: mytournamentx-api
    ports:
      - "8080:8080"
    environment:
      - ALLOWED_ORIGINS=${ORIGINS:-http://localhost}
      - DEFAULT_PASSWORD=password
  mytournamentx:
    image: udlepssoftarch/mytournamentx
    container_name: mytournamentx
    ports:
      - "80:80"
    environment:
      - API_URL=${API_URL:-http://localhost:8080}
